---
title: "project_code"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
library(readr)
library(ggplot2)
library(dplyr)
```

## Data Acquisition & Cleaning - Luis Barraza

```{r}
sheet1 <- read_csv("data/Microbes data - 2023.csv")
```

```{r}
sheet2 <- read_csv("data/Microbes data - 2024.csv")
```

```{r}
sheet3 <- read_csv("data/Microbes data - 2026.csv")
```

```{r}
clean1 <- sheet1 %>% clean_names() %>%
  mutate(media_na_or_sda=as.factor(media_na_or_sda),
         inside_or_outside=as.factor(inside_or_outside),
         exposure_duration_min=as.factor(exposure_duration_min),
         section=as.factor(section),
         media_additive_none_cyc_or_amp=as.factor(media_additive_none_cyc_or_amp)) %>%
  mutate(media_na_or_sda= recode(media_na_or_sda,
                                   "NA"="NUA",
                                   "SDA"="SDA")) %>%
  mutate(media_na_or_sda = forcats::fct_na_value_to_level(media_na_or_sda, level = "NUA")) %>% # - Alan (Googled)
  mutate(year = "2023") %>% #added to mark year of data - Alan 
  select(!c("group_name","notes"))
```

```{r}
clean2 <-  sheet2 %>% clean_names() %>%
  mutate(media_na_or_sda=as.factor(media_na_or_sda),
         inside_or_outside=as.factor(inside_or_outside),
         exposure_duration_min=as.factor(exposure_duration_min),
         section=as.factor(section),
         media_additive_none_cyc_or_amp=as.factor(media_additive_none_cyc_or_amp)) %>%
  mutate(media_na_or_sda= recode(media_na_or_sda,
                                   "NA"="NUA",
                                   "SDA"="SDA")) %>%
  mutate(media_na_or_sda = forcats::fct_na_value_to_level(media_na_or_sda, level = "NUA")) %>% # - Alan (Googled)
  mutate(media_additive_none_cyc_or_amp= recode(media_additive_none_cyc_or_amp,
                                   "ampicillin"="amp",
                                   "Cycloheximide 0.0004%"= "cyc",
                                   "AMP 50ug"="amp",
                                   "AMP 50 ug"="amp")) %>%
  mutate(year = "2024") %>% #added to mark year of data - Alan 
  select(!c("group_name","notes"))
```


```{r}
clean3 <- sheet3 %>% clean_names() %>%
  mutate(media_na_or_sda=as.factor(media_na_or_sda),
         inside_or_outside=as.factor(inside_or_outside),
         exposure_duration_min=as.factor(exposure_duration_min),
         section=as.factor(section),
         media_additive_none_cyc_or_amp=as.factor(media_additive_none_cyc_or_amp)) %>%
  mutate(media_na_or_sda= recode(media_na_or_sda,
                                   "NA"="NUA",
                                   "SDA"="SDA")) %>%
  mutate(media_additive_none_cyc_or_amp= recode(media_additive_none_cyc_or_amp,
                                   "CHX"="cyc",
                                   "Amp"= "amp",
                                   "AMP"="amp",
                                   "AMP 50 ug"="amp")) %>%
  mutate(inside_or_outside= recode(inside_or_outside,
                                   "Inside"="inside",
                                   "inside"="inside",
                                   "Outside"="outside",
                                   "outside"="outside")) %>%
  mutate(across(where(is.list), as.double)) %>%
  mutate(media_na_or_sda = forcats::fct_na_value_to_level(media_na_or_sda, level = "NUA")) %>% # - Alan (Googled)
  mutate(year="2026") %>% #added to mark year of data - Alan 
  mutate(number_mold_looking_colonies_have_hyphae = is.numeric(number_mold_looking_colonies_have_hyphae)) %>% # - Alan
  rename(total_number_colonies=total_number_colonies_both_mold_non_mold_colonies_cumulative_counts_from_both_days)%>%
  select(!c("group_name","notes", "name_of_the_data_recorder"))
  #mutate(number_mold_looking_colonies_have_hyphae=recode(number_mold_looking_colonies_have_hyphae,
                                               #          "NA"=0))
```

```{r}
fulldata <- bind_rows(clean1, clean2, clean3) %>% # - Alan
    mutate(resistance = case_when( # true/false on if there is resistance 
        media_na_or_sda == "NUA" & number_mold_looking_colonies_have_hyphae >= 1 ~ "T",
        media_na_or_sda == "NUA" & number_mold_looking_colonies_have_hyphae < 1 ~ "F",
        media_na_or_sda == "SDA" & number_non_mold_looking_colonies_e_g_no_hyphae >= 1 ~ "T",
        media_na_or_sda == "SDA" & number_non_mold_looking_colonies_e_g_no_hyphae < 1 ~ "F",
        TRUE ~ "Unknown")) %>% 
    rename(mold_col=number_mold_looking_colonies_have_hyphae) %>%
    rename(bact_col=number_non_mold_looking_colonies_e_g_no_hyphae)

#Old method:
#test <- full_join(clean1, clean2, clean3, by = c("section", "media_na_or_sda", "media_additive_none_cyc_or_amp", "inside_or_outside", "exposure_duration_min",  "days_of_incubation", "number_mold_looking_colonies_have_hyphae", "number_non_mold_looking_colonies_e_g_no_hyphae", "total_number_colonies", "year"), relationship = "many-to-many") # merging csv files - Alan
#fulldata <- full_join(test, clean3, by = c("section", "media_na_or_sda", "media_additive_none_cyc_or_amp", "inside_or_outside", "exposure_duration_min",  "days_of_incubation", "number_mold_looking_colonies_have_hyphae", "number_non_mold_looking_colonies_e_g_no_hyphae", "total_number_colonies", "year"), relationship = "many-to-many") # merging csv files pt 2 - Alan 
```


# Extra Analysis/Plotting - Luis Barraza
RUNS A BOXPLOT MAPPING RESISTANCE OVER THE YEARS
```{r}
resistanced %>%
  filter(resistance!="Unknown") %>%
  mutate(year=as.factor(year)) %>%
  ggplot(aes(x=year, y=total_number_colonies)) +
  geom_boxplot(aes(fill = resistance))
```

COMPARES BOXPLOTS OF RESISTANCE INDOOR VS OUTDOOR
```{r}
resistanced %>%
  mutate(year=as.factor(year)) %>%
  filter(resistance!="Unknown") %>%
  ggplot(aes(x=year, y=total_number_colonies)) +
  geom_boxplot(aes(fill = resistance)) +
  facet_wrap(~inside_or_outside, ncol=2, labeller=label_both)
```

MAKES A NEW DATA SET COUNTING WHICH COLONY TYPE HAS MORE RESISTANCE
```{r}
resistancec <- fulldata %>%
  mutate(mresistance=case_when(media_na_or_sda== "NUA" & number_mold_looking_colonies_have_hyphae >=1 ~ "T",
                              media_na_or_sda=="NUA" & number_mold_looking_colonies_have_hyphae <1 ~"F",
                              TRUE ~ "Unknown")) %>%
  mutate(bresistance=case_when(media_na_or_sda=="SDA" & number_non_mold_looking_colonies_e_g_no_hyphae >=1 ~ "T",
                              media_na_or_sda=="SDA" &
                                number_non_mold_looking_colonies_e_g_no_hyphae <1 ~"F",
                              TRUE ~ "Unknown")) %>%
  rename(mold_col=number_mold_looking_colonies_have_hyphae) %>%
  rename(bact_col=number_non_mold_looking_colonies_e_g_no_hyphae)
```

COUNTS BACTERIAL RESISTANCE
```{r}
bactresist <- resistancec %>%
  filter(bresistance!="Unknown") %>%
  count(bresistance)
bactresist
```

COUNTS MOLD RESISTANCE
```{r}
molresist <- resistancec %>%
  filter(mresistance!="Unknown") %>%
  count(mresistance)
molresist
```

```{r}
#Microbes Graphs for 2023


#Bar Graph Visualization

fulldata %>%
  select(year,section,total_number_colonies) %>%
  filter(year == "2023") %>%
  ggplot(aes(x=section,y=total_number_colonies,fill = section))+
  geom_col()+
  coord_cartesian(ylim = c(0, 600)) +
  labs(title = "Section per Total Colony Counts",
       y="Total Colony Count")

fulldata %>%
  select(year,section,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  filter(year == "2023") %>%
  ggplot(aes(x=section,y=number_non_mold_looking_colonies_e_g_no_hyphae,fill = section))+
  geom_col()+
  coord_cartesian(ylim = c(0, 600)) +
  labs(title = "Section per Bacteria Looking Colonies",
       y="Total Bacteria Count")

fulldata %>%
  select(year,section,number_mold_looking_colonies_have_hyphae) %>%
  filter(year == "2023") %>%
  ggplot(aes(x=section,y=number_mold_looking_colonies_have_hyphae,fill = section))+
  geom_col()+
  coord_cartesian(ylim = c(0, 600)) +
  labs(title = "Section per Mold Looking Colonies",
       y="Total Mold Count")


#Boxplot Graph Visualization

fulldata2 %>%
  filter(year == "2023") %>%
  mutate(colony_type=recode(colony_type,
                            "number_non_mold_looking_colonies_e_g_no_hyphae"="bacterial_colonies",
                            "number_mold_looking_colonies_have_hyphae"="mold_colonies")) %>%
  ggplot(aes(x=location, y=colony_count, fill = colony_type))+
  geom_boxplot(position = position_dodge(width=.8))+
  facet_wrap(~location, scales="free")+
  labs(title = "Colony Counts Indoors vs Outdoors",
       x="Location",
       y="Total colony counts")+
  coord_cartesian(ylim = c(0, 210))

fulldata %>%
  select(year,media_add,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  filter(year == "2023") %>%
  ggplot(aes(x=media_add,y=number_non_mold_looking_colonies_e_g_no_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Bacteria Looking Colonies",
       x="Media Additive",
       y="Bacteria colony counts")+
  coord_cartesian(ylim = c(0, 200))

fulldata %>%
  select(year,media_add,number_mold_looking_colonies_have_hyphae) %>%
  filter(year == "2023") %>%
  ggplot(aes(x=media_add,y=number_mold_looking_colonies_have_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Mold Looking Colonies",
       x="Media Additive",
       y="Mold Colony Counts")+
  coord_cartesian(ylim = c(0, 200))


#Line Graph Visualization

fulldata %>%
  group_by(year,media_add, exposure_duration_min) %>%
  filter(year == "2023") %>%
  mutate(exposure_duration_min=as.factor(exposure_duration_min)) %>%
  summarize(mean_colony_counts = mean(total_number_colonies, na.rm = TRUE)) %>%
  ggplot(aes(x=exposure_duration_min,
             y=mean_colony_counts,
             group=media_add,
             color=media_add))+
  geom_line() +
  labs(title = "Growing Trends of Exposure",
       x="Exposure Duration minutes",
       y="Average Colony Counts per exposure time")
```
```{r}
#Microbes Graphs for 2024


#Bar Graph Visualization

fulldata %>%
  select(year,section,total_number_colonies) %>%
  filter(year == "2024") %>%
  ggplot(aes(x=section,y=total_number_colonies,fill = section))+
  geom_col()+
  coord_cartesian(ylim = c(0, 1300)) +
  labs(title = "Section per Total Colony Counts",
       y="Total Colony Count")

fulldata %>%
  select(year,section,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  filter(year == "2024") %>%
  ggplot(aes(x=section,y=number_non_mold_looking_colonies_e_g_no_hyphae,fill = section))+
  geom_col()+
  coord_cartesian(ylim = c(0, 1300)) +
  labs(title = "Section per Bacteria Looking Colonies",
       y="Total Bacteria Count")

fulldata %>%
  select(year,section,number_mold_looking_colonies_have_hyphae) %>%
  filter(year == "2024") %>%
  ggplot(aes(x=section,y=number_mold_looking_colonies_have_hyphae,fill = section))+
  geom_col()+
  coord_cartesian(ylim = c(0, 1300)) +
  labs(title = "Section per Mold Looking Colonies",
       y="Total Mold Count")


#Boxplot Graph Visualization

fulldata2 %>%
  filter(year == "2024") %>%
  mutate(colony_type=recode(colony_type,
                            "number_non_mold_looking_colonies_e_g_no_hyphae"="bacterial_colonies",
                            "number_mold_looking_colonies_have_hyphae"="mold_colonies")) %>%
  ggplot(aes(x=location, y=colony_count, fill = colony_type))+
  geom_boxplot(position = position_dodge(width=.8))+
  facet_wrap(~location, scales="free")+
  labs(title = "Colony Counts Indoors vs Outdoors",
       x="Location",
       y="Total colony counts")+
  coord_cartesian(ylim = c(0, 300))

fulldata %>%
  select(year,media_add,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  filter(year == "2024") %>%
  ggplot(aes(x=media_add,y=number_non_mold_looking_colonies_e_g_no_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Bacteria Looking Colonies",
       x="Media Additive",
       y="Bacteria colony counts")

fulldata %>%
  select(year,media_add,number_mold_looking_colonies_have_hyphae) %>%
  filter(year == "2024") %>%
  ggplot(aes(x=media_add,y=number_mold_looking_colonies_have_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Mold Looking Colonies",
       x="Media Additive",
       y="Mold Colony Counts")


#Line Graph Visualization

fulldata %>%
  group_by(year,media_add, exposure_duration_min) %>%
  filter(year == "2024") %>%
  mutate(exposure_duration_min=as.factor(exposure_duration_min)) %>%
  summarize(mean_colony_counts = mean(total_number_colonies, na.rm = TRUE)) %>%
  ggplot(aes(x=exposure_duration_min,
             y=mean_colony_counts,
             group=media_add,
             color=media_add))+
  geom_line() +
  labs(title = "Growing Trends of Exposure",
       x="Exposure Duration minutes",
       y="Average Colony Counts per exposure time")
```
```{r}
#Microbes Graphs for 2026

#Bar Graph Visualization

fulldata %>%
  select(year,section,total_number_colonies) %>%
  filter(year == "2026") %>%
  ggplot(aes(x=section,y=total_number_colonies,fill = section))+
  geom_col()+
  coord_cartesian(ylim = c(0, 1000)) +
  labs(title = "Section per Total Colony Counts",
       y="Total Colony Count")

fulldata %>%
  select(year,section,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  filter(year == "2026") %>%
  ggplot(aes(x=section,y=number_non_mold_looking_colonies_e_g_no_hyphae,fill = section))+
  geom_col()+
  coord_cartesian(ylim = c(0, 1000)) +
  labs(title = "Section per Bacteria Looking Colonies",
       y="Total Bacteria Count")

fulldata %>%
  select(year,section,number_mold_looking_colonies_have_hyphae) %>%
  filter(year == "2026") %>%
  ggplot(aes(x=section,y=number_mold_looking_colonies_have_hyphae,fill = section))+
  geom_col()+
  coord_cartesian(ylim = c(0, 1000)) +
  labs(title = "Section per Mold Looking Colonies",
       y="Total Mold Count")


#Boxplot Graph Visualization

fulldata2 %>%
  filter(year == "2026") %>%
  mutate(colony_type=recode(colony_type,
                            "number_non_mold_looking_colonies_e_g_no_hyphae"="bacterial_colonies",
                            "number_mold_looking_colonies_have_hyphae"="mold_colonies")) %>%
  ggplot(aes(x=location, y=colony_count, fill = colony_type))+
  geom_boxplot(position = position_dodge(width=.8))+
  facet_wrap(~location, scales="free") +
  labs(title = "Colony Counts Indoors vs Outdoors",
       x="Location",
       y="Total colony counts")+
   coord_cartesian(ylim = c(0, 200))

fulldata %>%
  select(year,media_add,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  filter(year == "2026") %>%
  ggplot(aes(x=media_add,y=number_non_mold_looking_colonies_e_g_no_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Bacteria Looking Colonies",
       x="Media Additive",
       y="Bacteria colony counts") +
  coord_cartesian(ylim = c(0, 200))

fulldata %>%
  select(year,media_add,number_mold_looking_colonies_have_hyphae) %>%
  filter(year == "2026") %>%
  ggplot(aes(x=media_add,y=number_mold_looking_colonies_have_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Mold Looking Colonies",
       x="Media Additive",
       y="Mold Colony Counts")+
  coord_cartesian(ylim = c(0, 200))


#Line Graph Visualization

fulldata %>%
  group_by(year,media_add, exposure_duration_min) %>%
  filter(year == "2026") %>%
  mutate(exposure_duration_min=as.factor(exposure_duration_min)) %>%
  summarize(mean_colony_counts = mean(total_number_colonies, na.rm = TRUE)) %>%
  ggplot(aes(x=exposure_duration_min,
             y=mean_colony_counts,
             group=media_add,
             color=media_add))+
  geom_line() +
  labs(title = "Growing Trends of Exposure",
       x="Exposure Duration minutes",
       y="Average Colony Counts per exposure time")
```
```{r}
resistanced %>%
  filter(resistance!="Unknown") %>%
  mutate(year=as.factor(year)) %>%
  ggplot(aes(x=year, y=total_number_colonies)) +
  geom_boxplot(aes(fill = resistance))+
  labs(title = "Antibiotic/Antifungal Resistance over the years",
       x="Years of study",
       y="Total colony counts")

```
```{r}
resistanced %>%
  mutate(year=as.factor(year)) %>%
  filter(resistance!="Unknown") %>%
  ggplot(aes(x=year, y=total_number_colonies)) +
  geom_boxplot(aes(fill = resistance)) +
  facet_wrap(~inside_or_outside, ncol=2, labeller=label_both) +
  labs(title = "Antibiotic/Antifungal resistance IN/OUT",
       x="Years",
       y="Total Colony Counts")
```
```{r}
bactresist <- resistancec %>%
  filter(bresistance!="Unknown") %>%
  count(bresistance)
bactresist
```
```{r}
molresist <- resistancec %>%
  filter(mresistance!="Unknown") %>%
  count(mresistance)
molresist
```

## Data Graphing - Luis Alvarez
```{r}
#This is for pivoting locations
fulldata <-  fulldata %>% 
  pivot_longer(cols="inside_or_outside",
               values_to = "location") %>% 
  mutate(location=str_to_title(location))

#This is for pivoting additives
fulldata <- fulldata %>% 
  pivot_longer(cols = "media_additive_none_cyc_or_amp",
               names_to = "media_additive",
               values_to = "media_add") %>% 
  mutate(media_add=str_to_title(media_add))

#To enable Faceting Otherwise Unnecessary
fulldata2 <- fulldata %>% 
  pivot_longer(cols = c("number_mold_looking_colonies_have_hyphae","number_non_mold_looking_colonies_e_g_no_hyphae"),
               names_to = "colony_type",
               values_to = "colony_count")

#Consistent for all three years


```


```{r}
#Microbes Graphs for 2023


#Bar Graph Visualization

fulldata %>% 
  select(year,section,total_number_colonies) %>%
  filter(year == "2023") %>%
  ggplot(aes(x=section,y=total_number_colonies,fill = section))+
  geom_col()+
  labs(title = "Section per Total Colony Counts")

fulldata %>% 
  select(year,section,number_non_mold_looking_colonies_e_g_no_hyphae) %>% 
  filter(year == "2023") %>%
  ggplot(aes(x=section,y=number_non_mold_looking_colonies_e_g_no_hyphae,fill = section))+
  geom_col()+
  labs(title = "Section per Bacteria Looking Colonies")

fulldata %>% 
  select(year,section,number_mold_looking_colonies_have_hyphae) %>% 
  filter(year == "2023") %>%
  ggplot(aes(x=section,y=number_mold_looking_colonies_have_hyphae,fill = section))+
  geom_col()+
  labs(title = "Section per Mold Looking Colonies")


#Boxplot Graph Visualization

fulldata2 %>% 
  filter(year == "2023") %>%
  ggplot(aes(x=location, y=colony_count, fill = colony_type))+
  geom_boxplot(position = position_dodge(width=.8))+
  facet_wrap(~location, scales="free")

fulldata %>% 
  select(year,media_add,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  filter(year == "2023") %>%
  ggplot(aes(x=media_add,y=number_non_mold_looking_colonies_e_g_no_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Bacteria Looking Colonies")

fulldata %>%
  select(year,media_add,number_mold_looking_colonies_have_hyphae) %>% 
  filter(year == "2023") %>%
  ggplot(aes(x=media_add,y=number_mold_looking_colonies_have_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Mold Looking Colonies")


#Line Graph Visualization

fulldata %>%
  group_by(year,media_add, exposure_duration_min) %>%
  filter(year == "2023") %>%
  summarize(mean_colony_counts = mean(total_number_colonies, na.rm = TRUE)) %>%
  ggplot(aes(x=exposure_duration_min,
             y=mean_colony_counts, 
             group=media_add,
             color=media_add))+
  geom_line()
```

```{r}
#Microbes Graphs for 2024

#Bar Graph Visualization

fulldata %>% 
  select(year,section,total_number_colonies) %>%
  filter(year == "2024") %>%
  ggplot(aes(x=section,y=total_number_colonies,fill = section))+
  geom_col()+
  labs(title = "Section per Total Colony Counts")

fulldata %>% 
  select(year,section,number_non_mold_looking_colonies_e_g_no_hyphae) %>% 
  filter(year == "2024") %>%
  ggplot(aes(x=section,y=number_non_mold_looking_colonies_e_g_no_hyphae,fill = section))+
  geom_col()+
  labs(title = "Section per Bacteria Looking Colonies")

fulldata %>% 
  select(year,section,number_mold_looking_colonies_have_hyphae) %>% 
  filter(year == "2024") %>%
  ggplot(aes(x=section,y=number_mold_looking_colonies_have_hyphae,fill = section))+
  geom_col()+
  labs(title = "Section per Mold Looking Colonies")


#Boxplot Graph Visualization

fulldata2 %>% 
  filter(year == "2024") %>%
  ggplot(aes(x=location, y=colony_count, fill = colony_type))+
  geom_boxplot(position = position_dodge(width=.8))+
  facet_wrap(~location, scales="free")

fulldata %>% 
  select(year,media_add,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  filter(year == "2024") %>%
  ggplot(aes(x=media_add,y=number_non_mold_looking_colonies_e_g_no_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Bacteria Looking Colonies")

fulldata %>%
  select(year,media_add,number_mold_looking_colonies_have_hyphae) %>% 
  filter(year == "2024") %>%
  ggplot(aes(x=media_add,y=number_mold_looking_colonies_have_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Mold Looking Colonies")


#Line Graph Visualization

fulldata %>%
  group_by(year,media_add, exposure_duration_min) %>%
  filter(year == "2024") %>%
  summarize(mean_colony_counts = mean(total_number_colonies, na.rm = TRUE)) %>%
  ggplot(aes(x=exposure_duration_min,
             y=mean_colony_counts, 
             group=media_add,
             color=media_add))+
  geom_line()
```

```{r}
#Microbes Graphs for 2026
#Bar Graph Visualization

fulldata %>% 
  select(year,section,total_number_colonies) %>%
  filter(year == "2026") %>%
  ggplot(aes(x=section,y=total_number_colonies,fill = section))+
  geom_col()+
  labs(title = "Section per Total Colony Counts")

fulldata %>% 
  select(year,section,number_non_mold_looking_colonies_e_g_no_hyphae) %>% 
  filter(year == "2026") %>%
  ggplot(aes(x=section,y=number_non_mold_looking_colonies_e_g_no_hyphae,fill = section))+
  geom_col()+
  labs(title = "Section per Bacteria Looking Colonies")

fulldata %>% 
  select(year,section,number_mold_looking_colonies_have_hyphae) %>% 
  filter(year == "2026") %>%
  ggplot(aes(x=section,y=number_mold_looking_colonies_have_hyphae,fill = section))+
  geom_col()+
  labs(title = "Section per Mold Looking Colonies")


#Boxplot Graph Visualization

fulldata2 %>% 
  filter(year == "2026") %>%
  ggplot(aes(x=location, y=colony_count, fill = colony_type))+
  geom_boxplot(position = position_dodge(width=.8))+
  facet_wrap(~location, scales="free")

fulldata %>% 
  select(year,media_add,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  filter(year == "2026") %>%
  ggplot(aes(x=media_add,y=number_non_mold_looking_colonies_e_g_no_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Bacteria Looking Colonies")

fulldata %>%
  select(year,media_add,number_mold_looking_colonies_have_hyphae) %>% 
  filter(year == "2026") %>%
  ggplot(aes(x=media_add,y=number_mold_looking_colonies_have_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Mold Looking Colonies")


#Line Graph Visualization

fulldata %>%
  group_by(year,media_add, exposure_duration_min) %>%
  filter(year == "2026") %>%
  summarize(mean_colony_counts = mean(total_number_colonies, na.rm = TRUE)) %>%
  ggplot(aes(x=exposure_duration_min,
             y=mean_colony_counts, 
             group=media_add,
             color=media_add))+
  geom_line()
```
```{r}
#Microbes Graphs for All years
#Bar Graph Visualization

fulldata %>% 
  select(section,total_number_colonies) %>%
  ggplot(aes(x=section,y=total_number_colonies,fill = section))+
  geom_col()+
  labs(title = "Section per Total Colony Counts")

fulldata %>% 
  select(section,number_non_mold_looking_colonies_e_g_no_hyphae) %>% 
  ggplot(aes(x=section,y=number_non_mold_looking_colonies_e_g_no_hyphae,fill = section))+
  geom_col()+
  labs(title = "Section per Bacteria Looking Colonies")

fulldata %>% 
  select(section,number_mold_looking_colonies_have_hyphae) %>% 
  ggplot(aes(x=section,y=number_mold_looking_colonies_have_hyphae,fill = section))+
  geom_col()+
  labs(title = "Section per Mold Looking Colonies")


#Boxplot Graph Visualization

fulldata2 %>% 
  ggplot(aes(x=location, y=colony_count, fill = colony_type))+
  geom_boxplot(position = position_dodge(width=.8))+
  facet_wrap(~location, scales="free")

fulldata %>% 
  select(media_add,number_non_mold_looking_colonies_e_g_no_hyphae) %>%
  ggplot(aes(x=media_add,y=number_non_mold_looking_colonies_e_g_no_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Bacteria Looking Colonies")

fulldata %>%
  select(media_add,number_mold_looking_colonies_have_hyphae) %>% 
  ggplot(aes(x=media_add,y=number_mold_looking_colonies_have_hyphae,color=media_add))+
  geom_boxplot()+
  labs(title = "Media Additive per Mold Looking Colonies")


#Line Graph Visualization

fulldata %>%
  group_by(media_add, exposure_duration_min) %>%
  summarize(mean_colony_counts = mean(total_number_colonies, na.rm = TRUE)) %>%
  ggplot(aes(x=exposure_duration_min,
             y=mean_colony_counts, 
             group=media_add,
             color=media_add))+
  geom_line()
```


## Shiny App - Alan Vongsavanh
```{r}
library(shiny)
library(shinydashboard)
```

```{r, eval=F, echo=T}
ui <- dashboardPage(
  
  dashboardHeader(title="Microbe Data"),
  
  dashboardSidebar(
  
    selectInput("year",
              "Dataset Year:",
              choices=sort(c("all", "2023", "2024", "2026")),
              selected="all"),
    
    selectInput("plot",
              "Select Plot Type",
              choices = c("bar", "boxplot", "line"),
              selected="bar"),
  
    selectInput("x",
              "Select X Axis", 
              choices = c("section", "media_na_or_sda", "media_additive_none_cyc_or_amp", "inside_or_outside", "exposure_duration_min",  "days_of_incubation", "number_mold_looking_colonies_have_hyphae", "number_non_mold_looking_colonies_e_g_no_hyphae", "total_number_colonies", "year", "location", "media_add"),
              selected="bar"),
  
      selectInput("y",
              "Select Y Axis",
              choices = c("section", "media_na_or_sda", "media_additive_none_cyc_or_amp", "inside_or_outside", "exposure_duration_min",  "days_of_incubation", "number_mold_looking_colonies_have_hyphae", "number_non_mold_looking_colonies_e_g_no_hyphae", "total_number_colonies", "year", "location", "media_add"),
              selected="total_number_colonies")
    
  ),
    
    dashboardBody(
      
    plotOutput("plot", width="500px", height="400px")
    
  )
  
)

server <- function(input, output, session) {
  
  output$plot <- renderPlot({
    
   # fulldata %>% 
    #  ggplot(aes(.data[[input$y]]))+
    #  geom_density(fill="steelblue",
    #               color="black",
     #              alpha=0.6)+
    #  theme_light()
    
    #code to filter the year options
    if (input$year == "2023") { 
      fulldata <- fulldata %>% 
        filter(year == 2023)
    }
    else if (input$year == "2024") {
      fulldata <- fulldata %>% 
        filter(year == 2024)
    } 
    else if (input$year == "2026") {
      fulldata <- fulldata %>%
        filter(year == 2026)
    }
  
    #code for plotting
    if (input$plot == "bar") {
      fulldata %>% 
        ggplot(aes(x = .data[[input$x]], y = .data[[input$y]], fill = year)) + 
        geom_col() +
        labs(title = "Total Colony Counts per Section") 
      }
    
    else if (input$plot == "boxplot") {
      fulldata %>%   
        ggplot(aes(x = .data[[input$x]], y = .data[[input$y]], color = year)) +
        geom_boxplot() +
        labs(title = "Total Number of Colonies by Media Additive")
      }

    else if (input$plot == "line") {
      fulldata %>%
       ggplot(aes(x = .data[[input$x]], y = .data[[input$y]])) + 
        geom_line()
        labs(title = "Growth Over Time")
      }
    
  })
  
}

shinyApp(ui, server)
```

